### ISSUE TITLE
Is this code open source?

### ISSUE THREAD

**Issue by kartben** [Rantanen/node-dtls#14]
There does not seem to be any open source license associated to this project? Can you shed some light on whether it is indeed open source, and if yes what is the license?

**Comment by Rantanen** [comment]
Oh. Seems like I've forgotten the LICENSE file. Sorry for that.

The package.json lists the license as ISC though. That's the intended license.

**Comment by Rantanen** [comment]
Added a LICENSE file.

**Comment by kartben** [comment]
Thanks! :)
