### ISSUE TITLE
alternative implementation

### ISSUE THREAD

**Issue by reklatsmasters** [Rantanen/node-dtls#19]
Hello, @Rantanen! Almost a one year ago i began [nodertc](http://github.com/nodertc) - pure js webrtc implementation (datachannel layer). WebRTC required dtls as one of transport layers. A few weeks ago i finished second step of my implementation - i released [nodertc/dtls](https://github.com/nodertc/dtls). Right now it's client-side impl. only with lightweight architecture.

I planned to maintain my `dtls` module. Yours `dtls` impl. seems unmaintained. Could you add a link to https://github.com/nodertc/dtls as maintained alternative? :cat:

**Comment by Rantanen** [comment]
Great work! Webrtc was my aim as well, but I ran out of motivation with the dtls implementation. :)
