### ISSUE TITLE
Improve HelloVerifyRequest cookie generation to use something verifiable

### ISSUE THREAD

**Issue by brycekahle** [Rantanen/node-dtls#5]
The RFC suggests (SHOULD) to base the cookie off a random secret and client parameters.

> The DTLS server SHOULD generate cookies in such a way that they can be verified without retaining
> any per-client state on the server. One technique is to have a randomly generated secret and generate > cookies as:
> 
> ```Cookie = HMAC(Secret, Client-IP, Client-Parameters)```
> 
> When the second ClientHello is received, the server can verify that
> the Cookie is valid and that the client can receive packets at the
> given IP address.

**Comment by Rantanen** [comment]
I'll fix this when I touch the sequence number. Unfortunately there's still a lot of low effort stuff just to get the handshake working quick instead of to get it working well.

Incoming message validation and sending proper faults is another large aspect that's severely lacking.
